spring:
  datasource:
    url: jdbc:postgresql://192.168.0.181:5432/HIRING_PLATFORM
    username : postgres
    password : myPassword 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server :
  port : 8081