spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HIRING_PLATFORM
    username : postgres
    password : myPassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      database: HIRING_PLATFORM
      uri: mongodb+srv://deepan:PHp4VnpK2aCwX2Q7@mcqresult.ze52fxm.mongodb.net/

server:
  tomcat:
    threads:
      max: 200
  port: 8081

