spring:
  datasource:
    url: jdbc:postgresql://192.168.0.181:5432/HIRING_PLATFORM
    username : postgres
    password : myPassword 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri = mongodb+srv://root:rathinam@cluster0:tiy85wb:mongodb:net/Result

server :
  port : 8081
